---

- name: Add sury php repository
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == 'Ubuntu'

- block:
    - name: APT | Install sury dependencies
      apt:
        name: "{{ item }}"
        state: latest
        dpkg_options: 'force-confnew,force-confdef'
        autoclean: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      with_items:
      - apt-transport-https
      - ca-certificates
      - lsb-release

    - name: APT_KEY | Install GPG key
      apt_key:
        url: "http://packages.sury.org/php/apt.gpg"
        state: present

    - name: APT_REPOSITORY | Add APT repository
      apt_repository:
        repo: "deb http://packages.sury.org/php {{ ansible_distribution_release }} main"

  when: ansible_distribution == 'Debian'
...
