---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    sury_php_packages:
    - php8.3

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-sury_php
...
