---
- name: Converge
  hosts: all
  vars:
    sury_php_packages:
    - php8.2
    - php8.2-gd
    - php8.2-mysql
  tasks:
  - name: "Include andrelohmann.sury_php"
    include_role:
      name: "andrelohmann.sury_php"
...
