---
- name: Converge
  hosts: all
  vars:
    sury_php_packages:
    - php8.2
    - php8.2-gd
    - php8.2-mysql
  roles:
  - andrelohmann.sury_php
  tasks:
  - name: "Include andrelohmann.apache_php"
    include_role:
      name: "andrelohmann.apache_php"
...
